name: test-integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js v8
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install
        run: npm install
      - name: Test
        run: docker-compose up --exit-code-from web